### ISSUE TITLE
Consumable items not working / vanishing on server

### ISSUE THREAD

**Issue by elMooXos** [Opeey/minecraft-hotbar-refill#1]
This applies to v1.1.0, when trying to drink potions / milk, effect is either not triggered or the item might even disappear altogether. Playing on a PaperSpigot server in latest version, with a pretty good ping.

Rolling back to 1.0.0 fixed the issue (obviously, as it doesnt include consumed items), and works really well with all the placed items (haven't tried with tools/weapons)

I'm not too sure what causes the issue but it might be that the swap is triggered too fast? A config file with the option to set delay / which types of item refill you want to use could be good.

(Thx for this great plugin)

**Comment by Opeey** [comment]
Thank you for your feedback. Looks like i missed this issue. I think you‘re right and the item might get removed from the inventory to early. I will look further into it, as soon as i have the time.

**Comment by BumbleTree** [comment]
I came to report also vanishing items here is the exact wording from my player today "Drink Milk, get new bucket of milk in hand, empty bucket gone"

**Comment by Opeey** [comment]
It took me a while, but the problems with consumables should be fixed with the new 1.1.1 release.
Please feel free to open a new issue if you encounter any other bugs.

[HotbarRefill-1.1.1](https://github.com/Opeey/minecraft-hotbar-refill/releases/tag/1.1.1)
